version: "3.8"

services:
  kv:
    container_name: express_db
    image: eqalpha/keydb
    entrypoint: ["keydb-server", "/etc/keydb.conf"]
    expose:
      - "6379"
    volumes:
      - ./keydb.conf:/etc/keydb.conf

  app:
    container_name: express_service
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: denoland/deno:alpine
    ports:
      - "${API_HOST:-0.0.0.0}:${API_PORT:-3002}:8500/tcp"
